<?
define("ID_IBLOCK_RECENZ", 5);
define("UF_AUTHOR_STATUS", "UF_AUTHOR_STATUS");
define("ID_UF_AUTHOR_STATUS_PUBLIC", 35);
define("ID_USER_GROUP_AUTHOR", 6);
define("FIX_AUDIT_TYPE_ID", "ex2_590");
define("PROPERTY_AUTHOR_ID", 9);